version: "0.2.0-{build}"
skip_tags: true
clone_depth: 1
skip_branch_with_pr: true
image: Ubuntu2004
stack: jdk 11
cache:
  - ~/.gradle/wrapper/dists -> ./gradle/wrapper/gradle-wrapper.properties

before_build:
  - sh: java -version
  - sh: touch ./disable-android.gradle # AppVeyor does not support Android
  - sh: ./gradlew --version --console plain

build_script:
  - sh: ./gradlew deploy_ToLocal --console plain

test_script:
  - sh: ./gradlew test  --console plain