version: "0.2.0-{build}"
skip_tags: true
clone_depth: 1
skip_branch_with_pr: true
image: Ubuntu2004
stack: jdk 11
before_build:
  - sh: java -version

build_script:
  - sh: ./gradlew deployJavaToLocal --console plain

test_script:
  - sh: ./gradlew test  --console plain